### ISSUE TITLE
Please update 'HandyJson' Version 

### ISSUE THREAD

**Issue by BoYuanZjq** [sacOO7/socketcluster-client-swift#22]
the new 'HandyJson' Version is 4.2,new xcode not support swift2.x,please update HandyJson

**Comment by sacOO7** [comment]
Hi @BoYuanZjq , we had some serious discussion about this in previous issue. You can find the details here #15 . But I think since everyone is migrating towards latest version of swift (swift-4.2), I updated HandyJson version to support latest version. It is referenced in above commit. Currently it should be available on swift package manager. I am not able to upload it on cocoapod, because my internet is not working properly. I might be able to do that till Sunday. So, you option is to use swift package manager to add the dependency or directly add the source code of the package in xcodeproj. As a module.

**Comment by sacOO7** [comment]
Hi @BoYuanZjq , can you install latest version of pod.... I believe the fix is now available on cocoapods....

**Comment by BoYuanZjq** [comment]
YES,I've achieved that，thanks


张坚强
铂渊信息技术（上海）有限公司
地址：杨浦区殷行路1286号嘉誉国际2号楼901室
电话：65650071-806
邮编：200438


原始邮件
发件人:sachin shindenotifications@github.com
收件人:sacOO7/socketcluster-client-swiftsocketcluster-client-swift@noreply.github.com
抄送:Derekzhangjianqiang@dync.cc; Mentionmention@noreply.github.com
发送时间:2018年11月12日(周一) 18:14
主题:Re: [sacOO7/socketcluster-client-swift] Please update 'HandyJson'Version (#22)


Hi @BoYuanZjq , can you install latest version of pod.... I believe the fix is now available on cocoapods....

**Comment by sacOO7** [comment]
Hi @BoYuanZjq , feel free to raise more issues 👍
